grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
      cert-manager.io/cluster-issuer: mkcert-issuer
    path: /

    # pathType is only for k8s >= 1.1=
    pathType: Prefix

    hosts:
      - grafana.hello.dev.kind
    ## Extra paths to prepend to every host configuration. This is useful when working with annotation based services.
    extraPaths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: loki-grafana
            port:
              number: 80
    tls:
      - hosts:
          - grafana.hello.dev.kind
        secretName: grafana-hello-ingress-cert

prometheus:
  enabled: true
loki:
  image:
    tag: 2.8.11
